/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SchoolUtilities API
 * OpenAPI spec version: 1.0
 */

export interface AddCourseDto {
  name: string;
  courseDescription: string;
  schoolUUID: string;
  persons: string[];
  classes: string[];
}
