/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SchoolUtilities API
 * OpenAPI spec version: 1.0
 */

export interface AddCourseDTO {
  courseName: string;
  courseDescription: string;
  schoolUUID: string;
  schoolSubjectUUID: string;
  users: string[];
  courseClasses: string[];
}
