/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SchoolUtilities API
 * OpenAPI spec version: 1.0
 */

export interface AddDepartmentDTO {
  departmentName: string;
  departmentAbbreviation: string;
  schoolUUID: string;
  departmentIsVisible: boolean;
  departmentChildsVisible: boolean;
  schoolClasses: string[];
}
