/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SchoolUtilities API
 * OpenAPI spec version: 1.0
 */

export interface AddSchoolRoomDTO {
  schoolUUID: string;
  schoolRoomName: string;
  schoolRoomAbbreviation: string;
  schoolRoomBuilding: string;
}
