/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SchoolUtilities API
 * OpenAPI spec version: 1.0
 */

export interface AddSchoolClassDTO {
  schoolClassName: string;
  schoolClassDepartmentUUID: string;
}
