/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SchoolUtilities API
 * OpenAPI spec version: 1.0
 */
import type { User } from "./user";

export interface Article {
  articleUUID: string;
  articleHeadline: string;
  articleCatchPhrase: string;
  articleContent: string;
  articleType: number;
  articleIsPublic: boolean;
  articlePublishTimestamp: string;
  articleCreationTimestamp: string;
  creator: User;
  readingTime: number;
}
