/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SchoolUtilities API
 * OpenAPI spec version: 1.0
 */
import type { School } from "./school";
import type { SchoolSubject } from "./schoolSubject";
import type { User } from "./user";
import type { SchoolClass } from "./schoolClass";
import type { CourseElement } from "./courseElement";
import type { FileSubmissionGrade } from "./fileSubmissionGrade";

export interface Course {
  /** The UUID of the course */
  courseUUID: string;
  /** The name of the course */
  courseName: string;
  /** The description of the course */
  courseDescription: string;
  /** The schoool of a course */
  school: School;
  /** The subject of a course */
  schoolSubject: SchoolSubject;
  /** The creation timestamp of the course */
  courseCreationTimestamp: string;
  /** The creator a the course */
  creator: User;
  /** Whether user is permitted to edit */
  canEdit: boolean;
  /** The users of a course */
  courseUsers: User[];
  /** The classes of a course */
  courseClasses: SchoolClass[];
  /** The elements of a course */
  courseElements: CourseElement[];
  /** The grades of a course */
  courseGrades: FileSubmissionGrade[];
}
