/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SchoolUtilities API
 * OpenAPI spec version: 1.0
 */

export interface Holiday {
  /** The UUID of the holiday */
  holidayUUID: string;
  /** The name of the holiday */
  holidayName: string;
  /** The startdate of the holiday */
  holidayStartDate: string;
  /** The enddate of the holiday */
  holidayEndDate: string;
}
