/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SchoolUtilities API
 * OpenAPI spec version: 1.0
 */
import type { Course } from "./course";
import type { Department } from "./department";
import type { JoinCode } from "./joinCode";
import type { User } from "./user";
import type { SchoolRoom } from "./schoolRoom";
import type { SchoolSubject } from "./schoolSubject";

export interface School {
  /** The courses of a school */
  courses: Course[];
  /** The departments of a school */
  departments: Department[];
  /** The join codes of a school */
  schoolJoinCodes: JoinCode[];
  /** The users of a school */
  schoolUsers: User[];
  /** The school rooms of a school */
  schoolRooms: SchoolRoom[];
  /** The subjects of a school */
  schoolSubjects: SchoolSubject[];
}
