/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SchoolUtilities API
 * OpenAPI spec version: 1.0
 */
import type { Course } from "./course";
import type { TimeTableElement } from "./timeTableElement";

export interface SchoolSubject {
  /** The UUID of the school subject */
  schoolSubjectUUID: string;
  /** The name of the school subject */
  schoolSubjectName: string;
  /** The abbreviation of the school subject */
  schoolSubjectAbbreviation: string;
  /** The courses of the school subject */
  courses: Course[];
  /** The time table elements of the school subject */
  timeTableElements: TimeTableElement[];
}
