import { colors } from "../colors/colors";

export const dark = {
  surfaceTint: colors.primary100,
  surfaceTintColor: colors.primary100,
  onErrorContainer: colors.error80,
  onError: colors.error20,
  errorContainer: colors.error30,
  onTertiaryContainer: colors.tertiary90,
  onTertiary: colors.tertiary20,
  tertiaryContainer: colors.tertiary30,
  tertiary: colors.tertiary80,
  shadow: colors.neutral0,
  error: colors.error80,
  outline: colors.neutralVariant60,
  outlineVariant: colors.neutralVariant30,
  onBackground: colors.neutral90,
  background: colors.neutral10,
  inverseOnSurface: colors.neutral20,
  inverseSurface: colors.neutral90,
  onSurfaceVariant: colors.neutralVariant80,
  onSurface: colors.neutral90,
  surfaceVariant: colors.neutralVariant30,
  surface: colors.neutral10,
  onSecondaryContainer: colors.secondary90,
  onSecondary: colors.secondary20,
  secondaryContainer: colors.secondary30,
  secondary: colors.secondary80,
  inversePrimary: colors.primary40,
  onPrimaryContainer: colors.primary90,
  onPrimary: colors.primary20,
  primaryContainer: colors.primary30,
  primary: colors.primary80,
};
