import { colors } from "../colors/colors";

export const light = {
  surfaceTint: colors.primary100,
  surfaceTintColor: colors.primary100,
  onErrorContainer: colors.error10,
  onError: colors.error100,
  errorContainer: colors.error90,
  onTertiaryContainer: colors.tertiary10,
  onTertiary: colors.tertiary100,
  tertiaryContainer: colors.tertiary90,
  tertiary: colors.tertiary40,
  shadow: colors.neutral0,
  error: colors.error40,
  outline: colors.neutralVariant50,
  outlineVariant: colors.neutralVariant80,
  onBackground: colors.neutral10,
  background: colors.neutral99,
  inverseOnSurface: colors.neutral95,
  inverseSurface: colors.neutral20,
  onSurfaceVariant: colors.neutralVariant30,
  onSurface: colors.neutral10,
  surfaceVariant: colors.neutralVariant90,
  surface: colors.neutral99,
  onSecondaryContainer: colors.secondary10,
  onSecondary: colors.secondary100,
  secondaryContainer: colors.secondary90,
  secondary: colors.secondary40,
  inversePrimary: colors.primary80,
  onPrimaryContainer: colors.primary10,
  onPrimary: colors.primary100,
  primaryContainer: colors.primary90,
  primary: colors.primary40,
  // mapped surface colors
  surface1: "#eff4f9",
  surface2: "#e8f0f7",
  surface3: "#dde9f2",
  surface4: "#dde9f2",
  surface5: "#d8e6f0",
};
