---
- hosts: all

  tasks:
    - name: "Install NPM repo"
      shell: curl -sL https://rpm.nodesource.com/setup_17.x | bash -
    - name: "Install NPM dependencies"
      yum:
        name:
          - nodejs
        state: latest